### ISSUE TITLE
About the use of QRhi

### ISSUE THREAD

**Issue by Italink** [alpqr/qrhibasis#2]
Excuse me, I want to use QRhi to do some graphics tutorials, will this violate the rights and interests of Qt company?

**Comment by alpqr** [comment]
Not at all, it is not different than any other Qt APIs. One thing to keep in mind however is that the QRhi APIs are all private (the application has to include _p.h headers and link to QtGuiPrivate as well), meaning that they do not come with source and binary compatibility guarantees at the moment, as opposed to public Qt APIs (the ones in .h headers).
